import { CalendarClock, ChevronLeft, ChevronRight, ClockAlert, ListChecks, Sunrise } from "lucide-react";
import Link from "next/link";
import { FollowUpCard } from "@/features/customers/customer-journey";
import { CUSTOMER_PRIORITIES, PRIORITY_LABELS } from "@/features/customers/types";
import { getFollowUpWorkspace } from "@/features/follow-ups/data";
import { parseFollowUpQuery } from "@/features/follow-ups/query";

export const metadata = { title: "Công việc chăm sóc" };

export default async function TasksPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = parseFollowUpQuery(await searchParams);
  const data = await getFollowUpWorkspace(query);
  const totalPages = Math.max(1, Math.ceil(data.count / data.pageSize));
  const href = (changes: Record<string, string | number>) => { const params = new URLSearchParams({ scope: query.scope, status: query.status, priority: query.priority, assignee: query.assignee, page: String(query.page) }); for (const [key, value] of Object.entries(changes)) params.set(key, String(value)); for (const [key, value] of [...params]) if (!value || (key === "page" && value === "1")) params.delete(key); return `/tasks?${params}`; };
  return <div className="mx-auto max-w-[1200px]"><header><p className="text-xs font-bold uppercase tracking-[.14em] text-[#728179]">Lịch chăm sóc</p><h1 className="mt-2 text-3xl font-bold tracking-[-.035em] sm:text-4xl">Công việc</h1><p className="mt-2 text-sm text-[#718078]">Ưu tiên các khách quá hạn, hôm nay và sắp tới theo danh sách bạn phụ trách.</p></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric href={href({ scope: "overdue", page: 1 })} active={query.scope === "overdue"} icon={ClockAlert} label="Quá hạn" value={data.summary.overdue} tone="rose" /><Metric href={href({ scope: "today", page: 1 })} active={query.scope === "today"} icon={Sunrise} label="Hôm nay" value={data.summary.today} tone="amber" /><Metric href={href({ scope: "upcoming", page: 1 })} active={query.scope === "upcoming"} icon={CalendarClock} label="Sắp tới" value={data.summary.upcoming} tone="green" /></section>
    <section className="card-shadow mt-5 rounded-[22px] border border-[#dfe7e2] bg-white"><form method="get" className="grid gap-3 border-b border-[#e4ebe7] p-4 sm:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="scope" value={query.scope} /><select name="status" defaultValue={query.status} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="pending">Đang mở</option><option value="completed">Hoàn thành</option><option value="cancelled">Đã hủy</option><option value="all">Mọi trạng thái</option></select><select name="priority" defaultValue={query.priority} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="">Mọi ưu tiên</option>{CUSTOMER_PRIORITIES.map((priority) => <option key={priority} value={priority}>{PRIORITY_LABELS[priority]}</option>)}</select><select name="assignee" defaultValue={query.assignee} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="">Mọi người phụ trách</option>{data.owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select><button className="focus-ring min-h-11 rounded-xl border border-[#cbd8d0] text-sm font-bold text-[#315d49]">Áp dụng</button></form>
      <div className="p-4 sm:p-5">{data.tasks.length ? <div className="space-y-4">{data.tasks.map((task) => <article key={task.id} className="rounded-2xl bg-[#f7f9f7] p-3"><div className="mb-2 flex items-center justify-between gap-3 px-1"><Link href={`/customers?customer=${task.customerId}`} className="focus-ring rounded-md text-sm font-bold text-[#176a4f] hover:underline">{task.customerName}</Link><span className="text-xs text-[#7b8982]">{task.teamName}</span></div><FollowUpCard task={task} /></article>)}</div> : <div className="grid min-h-52 place-items-center text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e8f1df] text-[#426344]"><ListChecks size={21} /></span><p className="mt-4 font-bold">Không có công việc phù hợp</p><p className="mt-1 text-sm text-[#7b8982]">Bạn đã xử lý hết nhóm công việc này.</p></div></div>}</div>
      <footer className="flex items-center justify-between border-t border-[#e9eeeb] px-4 py-4 text-sm text-[#69776f]"><span>{data.count} công việc · Trang {query.page}/{totalPages}</span><div className="flex gap-2"><Link href={href({ page: Math.max(1, query.page - 1) })} aria-disabled={query.page <= 1} className={`focus-ring grid size-10 place-items-center rounded-xl border border-[#dbe3de] ${query.page <= 1 ? "pointer-events-none opacity-40" : ""}`}><ChevronLeft size={17} /></Link><Link href={href({ page: Math.min(totalPages, query.page + 1) })} aria-disabled={query.page >= totalPages} className={`focus-ring grid size-10 place-items-center rounded-xl border border-[#dbe3de] ${query.page >= totalPages ? "pointer-events-none opacity-40" : ""}`}><ChevronRight size={17} /></Link></div></footer>
    </section></div>;
}

function Metric({ href, active, icon: Icon, label, value, tone }: { href: string; active: boolean; icon: typeof ClockAlert; label: string; value: number; tone: "rose" | "amber" | "green" }) {
  const tones = { rose: "bg-rose-50 text-rose-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700" };
  return <Link href={href} aria-current={active ? "page" : undefined} className={`focus-ring rounded-2xl border bg-white p-4 transition ${active ? "border-[#9ebc9f] shadow-sm" : "border-[#dfe7e2] hover:border-[#bfd0c5]"}`}><span className={`grid size-9 place-items-center rounded-xl ${tones[tone]}`}><Icon size={17} /></span><p className="mt-4 text-sm font-semibold text-[#68776f]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></Link>;
}
