import Link from "next/link";
import { BookOpen, ChevronRight, Download, File, FileArchive, FileImage, FileSpreadsheet, FileText, Folder, Search, ShieldCheck, X } from "lucide-react";
import { getDocumentsWorkspace } from "@/features/documents/data";
import { documentQueryString, parseDocumentQuery } from "@/features/documents/query";
import { DeleteDocumentForm, DocumentUploadForm, EmbeddingRetryForm, ExtractionActionForm, FolderForm, VersionUploadForm } from "@/features/documents/document-forms";
import type { EmbeddingStatus, ExtractionStatus } from "@/features/documents/types";

export const metadata = { title: "Kho tài liệu" };
const dateTime = new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", dateStyle: "short", timeStyle: "short" });
const size = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 1 });
function fileSize(bytes: number) { return bytes < 1_048_576 ? `${size.format(bytes / 1024)} KB` : `${size.format(bytes / 1_048_576)} MB`; }
const statusLabel: Record<ExtractionStatus, string> = { uploading: "Đang tải lên", pending: "Chờ xử lý", processing: "Đang đọc nội dung", ready: "Sẵn sàng", failed: "Cần xử lý lại", unsupported: "Chỉ có thể tải xuống" };
const embeddingLabel: Record<EmbeddingStatus, string> = { not_applicable: "Chưa sẵn sàng cho trợ lý", pending: "Đang chuẩn bị cho trợ lý", processing: "Đang chuẩn bị cho trợ lý", ready: "Có thể dùng với trợ lý AI", failed: "Chưa thể dùng với trợ lý AI" };

export default async function DocumentsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = parseDocumentQuery(await searchParams); const data = await getDocumentsWorkspace(query); const manager = data.viewer.role === "admin" || data.viewer.role === "leader";
  return <div className="mx-auto max-w-[1380px]">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#728179]">Tài liệu nội bộ</p><h1 className="mt-2 text-3xl font-bold tracking-[-.035em] sm:text-4xl">Kho tài liệu</h1><p className="mt-2 text-sm text-[#718078]">Tài liệu được bảo vệ và chỉ hiển thị cho người được cấp quyền.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#cfe0d3] bg-white px-3 py-2 text-xs font-semibold text-[#3d634f]"><ShieldCheck size={15} /> Truy cập an toàn</span></header>

    <div className={`mt-7 grid gap-5 ${manager ? "xl:grid-cols-[1fr_390px]" : ""}`}>
      <section className="card-shadow overflow-hidden rounded-[24px] border border-[#e0e7e2] bg-white">
        <form method="get" className="grid gap-3 border-b border-[#e5ebe7] p-4 md:grid-cols-2 xl:grid-cols-4"><label className="relative md:col-span-2"><Search className="absolute left-3 top-3.5 text-[#89968f]" size={17} /><input name="q" defaultValue={query.q} placeholder="Tìm theo tên tài liệu" className="focus-ring min-h-11 w-full rounded-xl border border-[#d8e2dc] pl-10 pr-3 text-sm" /></label><select name="scope" defaultValue={query.scope} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] bg-white px-3 text-sm"><option value="">Mọi phạm vi</option><option value="organization">Toàn công ty</option><option value="team">Theo nhóm</option><option value="user">Cá nhân</option></select><select name="extraction" defaultValue={query.extraction} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] bg-white px-3 text-sm"><option value="">Mọi trạng thái</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select name="folder" defaultValue={query.folder} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] bg-white px-3 text-sm"><option value="">Mọi thư mục</option>{data.folders.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="focus-ring min-h-11 rounded-xl border border-[#cbd8d0] text-sm font-bold text-[#315d49]">Áp dụng bộ lọc</button></form>
        {data.documents.length ? <div className="divide-y divide-[#edf1ee]">{data.documents.map((document) => <Link key={document.id} href={`/documents?${documentQueryString(query, { document: document.id })}`} className="focus-ring group grid gap-3 p-4 transition hover:bg-[#f7f9f7] sm:grid-cols-[48px_1fr_auto] sm:items-center sm:px-5"><span className="grid size-12 place-items-center rounded-2xl bg-[#edf3e3] text-[#426043]">{fileIcon(document.currentVersion?.mimeType)}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-bold">{document.title}</p>{document.currentVersion ? <StatusBadge status={document.currentVersion.extractionStatus} /> : null}</div><p className="mt-1 truncate text-xs text-[#7b8982]">{document.scopeName}{document.folderName ? ` · ${document.folderName}` : ""}{document.currentVersion ? ` · v${document.currentVersion.versionNo} · ${fileSize(document.currentVersion.sizeBytes)}` : ""}</p></div><div className="flex items-center gap-3 text-xs text-[#7b8982]"><span>{dateTime.format(new Date(document.updatedAt))}</span><ChevronRight className="text-[#a2ada7] transition group-hover:translate-x-0.5" size={17} /></div></Link>)}</div> : <div className="grid min-h-72 place-items-center p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#edf3e3] text-[#426043]"><BookOpen size={23} /></span><p className="mt-4 font-bold">{query.q || query.scope || query.extraction || query.folder ? "Không có tài liệu khớp bộ lọc" : "Kho tài liệu đang trống"}</p><p className="mt-1 text-sm text-[#7b8982]">{manager ? "Tải tài liệu đầu tiên từ khung quản lý bên cạnh." : "Trưởng nhóm hoặc quản trị viên sẽ cấp tài liệu phù hợp cho bạn."}</p></div></div>}
      </section>

      {manager ? <aside className="space-y-5"><section className="card-shadow rounded-[24px] border border-[#e0e7e2] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#7a8981]">Tải lên</p><h2 className="mt-2 text-xl font-bold">Thêm tài liệu</h2><p className="mt-2 text-sm leading-6 text-[#718078]">Tệp tối đa 25 MB. Khi cập nhật, phiên bản cũ vẫn được giữ lại.</p><DocumentUploadForm role={data.viewer.role as "admin" | "leader"} teamId={data.viewer.teamId} teams={data.teams} users={data.users} folders={data.folders} /></section><section className="card-shadow rounded-[24px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#f4ead7] text-[#7d5b2a]"><Folder size={18} /></span><div><p className="font-bold">Sắp xếp thư mục</p><p className="text-xs text-[#7b8982]">Giúp tìm tài liệu nhanh hơn</p></div></div><FolderForm role={data.viewer.role as "admin" | "leader"} teamId={data.viewer.teamId} teams={data.teams} users={data.users} /></section></aside> : null}
    </div>

    {data.selected ? <div className="fixed inset-0 z-40 bg-[#0d261d]/25 backdrop-blur-[2px]"><Link href={`/documents?${documentQueryString(query, { document: null })}`} aria-label="Đóng chi tiết" className="absolute inset-0" /><aside className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto border-l border-[#dce5df] bg-[#f8faf8] p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#728179]">Chi tiết tài liệu</p><h2 className="mt-2 text-2xl font-bold tracking-[-.025em]">{data.selected.title}</h2><p className="mt-2 text-sm text-[#718078]">{data.selected.scopeName}{data.selected.folderName ? ` · ${data.selected.folderName}` : ""}</p></div><Link href={`/documents?${documentQueryString(query, { document: null })}`} className="focus-ring grid size-10 shrink-0 place-items-center rounded-xl border border-[#dce5df] bg-white"><X size={18} /></Link></div>
          {data.selected.currentVersion ? <div className="mt-6 rounded-2xl bg-[#173c2f] p-5 text-white"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white/10 text-[#d9e8af]">{fileIcon(data.selected.currentVersion.mimeType)}</span><div className="min-w-0"><p className="truncate font-bold">{data.selected.currentVersion.fileName}</p><p className="mt-1 text-xs text-emerald-50/60">v{data.selected.currentVersion.versionNo} · {fileSize(data.selected.currentVersion.sizeBytes)} · {statusLabel[data.selected.currentVersion.extractionStatus]}{data.selected.currentVersion.extractionStatus === "ready" ? ` · ${embeddingLabel[data.selected.currentVersion.embeddingStatus]}` : ""}</p></div></div><Link href={`/documents/${data.selected.id}/open?version=${data.selected.currentVersion.id}`} target="_blank" className="focus-ring mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#d9e8af] px-4 text-sm font-bold text-[#173c2f]"><Download size={17} /> Mở hoặc tải tệp</Link></div> : null}
          <section className="mt-6"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#7a8981]">Lịch sử phiên bản</p><div className="mt-3 space-y-2">{data.versions.map((version) => <div key={version.id} className="rounded-2xl border border-[#e1e8e3] bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold">v{version.versionNo} · {version.fileName}</p><p className="mt-1 text-xs text-[#7b8982]">{fileSize(version.sizeBytes)} · {dateTime.format(new Date(version.createdAt))} · {version.uploaderName}</p>{version.extractionStatus === "ready" ? <p className="mt-1 text-xs text-[#62746a]">{embeddingLabel[version.embeddingStatus]}</p> : null}</div><StatusBadge status={version.extractionStatus} /></div>{version.extractionStatus === "failed" ? <p className="mt-2 text-xs text-rose-700">Không đọc được nội dung tài liệu. Hãy kiểm tra tệp và thử lại.</p> : null}{version.embeddingStatus === "failed" ? <p className="mt-2 text-xs text-amber-700">Chưa thể dùng tài liệu này với trợ lý AI. Bạn vẫn có thể tìm theo tên hoặc nội dung.</p> : null}<div className="flex flex-wrap items-end justify-between gap-2"><Link href={`/documents/${data.selected!.id}/open?version=${version.id}`} target="_blank" className="focus-ring mt-3 inline-flex items-center gap-2 rounded-lg text-xs font-bold text-[#315d49]"><Download size={14} /> Mở phiên bản này</Link>{data.selected!.canManage && (version.extractionStatus === "pending" || version.extractionStatus === "failed") ? <ExtractionActionForm versionId={version.id} status={version.extractionStatus} /> : null}{data.selected!.canManage && version.extractionStatus === "ready" && version.embeddingStatus === "failed" ? <EmbeddingRetryForm versionId={version.id} /> : null}</div></div>)}</div></section>
          {data.selected.canManage ? <section className="mt-6 rounded-2xl border border-[#e1e8e3] bg-white p-4"><p className="font-bold">Quản lý tài liệu</p><VersionUploadForm documentId={data.selected.id} /><DeleteDocumentForm documentId={data.selected.id} /></section> : null}
        </aside></div> : null}
  </div>;
}

function StatusBadge({ status }: { status: ExtractionStatus }) { const tone = status === "ready" ? "bg-emerald-50 text-emerald-700" : status === "failed" ? "bg-rose-50 text-rose-700" : "bg-[#f4ead7] text-[#7d5b2a]"; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-bold ${tone}`}>{statusLabel[status]}</span>; }
function fileIcon(mime?: string) { if (mime?.includes("spreadsheet")) return <FileSpreadsheet size={21} />; if (mime?.startsWith("image/")) return <FileImage size={21} />; if (mime?.includes("presentation")) return <FileArchive size={21} />; if (mime?.includes("pdf") || mime?.includes("word")) return <FileText size={21} />; return <File size={21} />; }
