"use client";

import { CalendarClock, CheckCircle2, CircleDot, Clock3, MessageSquareText } from "lucide-react";
import { useActionState } from "react";
import { manageFollowUpTaskAction, recordActivityAction, type CustomerActionState } from "./actions";
import { ACTIVITY_OUTCOME_LABELS, ACTIVITY_OUTCOMES, ACTIVITY_TYPE_LABELS, ACTIVITY_TYPES, CUSTOMER_PRIORITIES, PRIORITY_LABELS, type ActivityItem, type FollowUpTask } from "./types";

const initial: CustomerActionState = { ok: false, message: "" };
const control = "focus-ring min-h-10 w-full rounded-xl border border-[#d8e2dc] bg-white px-3 text-sm outline-none";
const formatDate = (value: string) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Ho_Chi_Minh" }).format(new Date(value));

export function CustomerJourney({ customerId, activities, followUps }: { customerId: string; activities: ActivityItem[]; followUps: FollowUpTask[] }) {
  const [state, action, pending] = useActionState(recordActivityAction, initial);
  const pendingTasks = followUps.filter((task) => task.status === "pending");
  return <section className="space-y-5">
    <details className="group rounded-2xl border border-[#dce6df] bg-white p-4" open={activities.length === 0}>
      <summary className="focus-ring flex cursor-pointer list-none items-center justify-between rounded-lg font-bold"><span className="flex items-center gap-2"><MessageSquareText size={18} className="text-[#176a4f]" /> Ghi hoạt động chăm sóc</span><span className="text-xs font-semibold text-[#6f7e76] group-open:hidden">Mở</span></summary>
      <form action={action} className="mt-4 space-y-3"><input type="hidden" name="customerId" value={customerId} />
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-[#596a61]">Loại hoạt động<select name="type" className={`${control} mt-1`} defaultValue="call">{ACTIVITY_TYPES.map((type) => <option key={type} value={type}>{ACTIVITY_TYPE_LABELS[type]}</option>)}</select></label><label className="text-xs font-bold text-[#596a61]">Kết quả<select name="outcome" className={`${control} mt-1`} defaultValue=""><option value="">Chưa xác định</option>{ACTIVITY_OUTCOMES.map((outcome) => <option key={outcome} value={outcome}>{ACTIVITY_OUTCOME_LABELS[outcome]}</option>)}</select></label></div>
        <label className="block text-xs font-bold text-[#596a61]">Nội dung<textarea name="content" maxLength={4000} className={`${control} mt-1 min-h-20 py-2.5`} placeholder="Tóm tắt trao đổi với khách" /></label>
        <label className="block text-xs font-bold text-[#596a61]">Thời gian xảy ra<input name="occurredAt" type="datetime-local" className={`${control} mt-1`} /><span className="mt-1 block font-normal text-[#87938d]">Để trống sẽ dùng thời điểm hiện tại.</span></label>
        <div className="rounded-xl bg-[#f5f8f4] p-3"><p className="text-xs font-bold text-[#506159]">Thêm lịch chăm sóc (không bắt buộc)</p><div className="mt-2 grid gap-3 sm:grid-cols-2"><input name="nextAction" className={control} maxLength={500} placeholder="Việc cần làm tiếp theo" /><input name="followUpAt" type="datetime-local" className={control} /></div><label className="mt-2 block text-xs font-bold text-[#596a61]">Ưu tiên<select name="priority" defaultValue="normal" className={`${control} mt-1`}>{CUSTOMER_PRIORITIES.map((priority) => <option key={priority} value={priority}>{PRIORITY_LABELS[priority]}</option>)}</select></label></div>
        {state.message && <p role="status" className={`rounded-xl px-3 py-2 text-sm ${state.ok ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{state.message}</p>}
        <div className="flex justify-end"><button disabled={pending} className="focus-ring min-h-10 rounded-xl bg-[#176a4f] px-4 text-sm font-bold text-white disabled:cursor-wait disabled:opacity-60">{pending ? "Đang lưu…" : "Lưu hoạt động"}</button></div>
      </form>
    </details>

    <div><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-bold"><CalendarClock size={18} className="text-[#b66b15]" /> Lịch chăm sóc sắp tới</h3><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">{pendingTasks.length}</span></div>{pendingTasks.length ? <div className="mt-3 space-y-3">{pendingTasks.map((task) => <FollowUpCard key={task.id} task={task} />)}</div> : <p className="mt-3 rounded-2xl border border-dashed border-[#d9e3dc] p-4 text-sm text-[#75837c]">Không có lịch chăm sóc đang mở.</p>}</div>

    <div><h3 className="flex items-center gap-2 font-bold"><CircleDot size={17} className="text-[#176a4f]" /> Lịch sử chăm sóc</h3>{activities.length ? <ol className="mt-4 space-y-0">{activities.map((activity, index) => <li id={`activity-${activity.id}`} key={activity.id} className="relative scroll-mt-5 grid grid-cols-[28px_1fr] gap-3 pb-5"><div className="relative flex justify-center"><span className="mt-1.5 size-2.5 rounded-full bg-[#6e9258] ring-4 ring-[#edf4e8]" />{index < activities.length - 1 && <span className="absolute bottom-[-6px] top-4 w-px bg-[#dce6df]" />}</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold">{ACTIVITY_TYPE_LABELS[activity.type] ?? activity.type}</p>{activity.outcome && <span className="rounded-full bg-[#f0f4f1] px-2 py-0.5 text-[11px] font-bold text-[#5e6f66]">{ACTIVITY_OUTCOME_LABELS[activity.outcome]}</span>}{activity.isLateEntry && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-bold text-amber-700">Nhập muộn</span>}</div><p className="mt-1 text-xs text-[#78867e]">{activity.performerName} · {formatDate(activity.occurredAt)}</p>{activity.content && <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#43564c]">{activity.content}</p>}{activity.nextAction && <p className="mt-2 flex items-center gap-1.5 text-xs font-semibold text-[#8a5b20]"><Clock3 size={13} /> {activity.nextAction} · {activity.followUpAt ? formatDate(activity.followUpAt) : ""}</p>}</div></li>)}</ol> : <p className="mt-3 rounded-2xl border border-dashed border-[#d9e3dc] p-5 text-center text-sm text-[#75837c]">Chưa có hoạt động. Hãy ghi lần tương tác đầu tiên.</p>}</div>
  </section>;
}

export function FollowUpCard({ task }: { task: FollowUpTask }) {
  const [state, action, pending] = useActionState(manageFollowUpTaskAction, initial);
  const overdue = new Date(task.dueAt) < new Date();
  return <details className="rounded-2xl border border-[#e2e8e4] bg-white p-3"><summary className="focus-ring cursor-pointer list-none rounded-lg"><div className="flex items-start gap-3"><span className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-xl ${task.status !== "pending" ? "bg-slate-100 text-slate-600" : overdue ? "bg-rose-50 text-rose-600" : "bg-amber-50 text-amber-700"}`}>{overdue && task.status === "pending" ? <Clock3 size={16} /> : <CheckCircle2 size={16} />}</span><div className="min-w-0"><p className="text-sm font-bold">{task.nextAction}</p><p className={`mt-1 text-xs ${overdue && task.status === "pending" ? "font-bold text-rose-600" : "text-[#75837c]"}`}>{formatDate(task.dueAt)} · {task.assigneeName} · {PRIORITY_LABELS[task.priority]}</p></div></div></summary>{task.status === "pending" ? <form action={action} className="mt-3 space-y-2 border-t border-[#edf1ee] pt-3"><input type="hidden" name="taskId" value={task.id} /><select name="action" defaultValue="complete" className={control}><option value="complete">Hoàn thành</option><option value="reschedule">Dời lịch</option><option value="cancel">Hủy lịch</option></select><input type="datetime-local" name="dueAt" className={control} aria-label="Lịch mới khi dời" /><input name="reason" required minLength={3} maxLength={500} className={control} placeholder="Kết quả hoặc lý do" />{state.message && <p role="status" className={`text-xs ${state.ok ? "text-emerald-700" : "text-rose-700"}`}>{state.message}</p>}<button disabled={pending} className="focus-ring min-h-9 rounded-xl border border-[#cbd8d0] px-3 text-xs font-bold text-[#315d49] disabled:opacity-60">{pending ? "Đang xử lý…" : "Xác nhận"}</button></form> : <p className="mt-3 border-t border-[#edf1ee] pt-3 text-xs text-[#68776f]">{task.status === "completed" ? "Đã hoàn thành" : "Đã hủy"}{task.completionReason ? ` · ${task.completionReason}` : ""}</p>}</details>;
}
