import { Banknote, ChevronLeft, ChevronRight, ContactRound, ReceiptText } from "lucide-react";
import Link from "next/link";
import { DealCard } from "@/features/deals/customer-deals";
import { buildDealAmendmentKeys } from "@/features/deals/amendment-access";
import { getDealsWorkspace } from "@/features/deals/data";
import { parseDealQuery } from "@/features/deals/query";

export const metadata = { title: "Giao dịch" };
const money = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });

export default async function DealsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = parseDealQuery(await searchParams); const data = await getDealsWorkspace(query);
  const amendmentKeys = buildDealAmendmentKeys(data.deals, data.viewer);
  const totalPages = Math.max(1, Math.ceil(data.count / data.pageSize));
  const href = (page: number) => { const params = new URLSearchParams({ status: query.status, owner: query.owner, team: query.team, source: query.source, from: query.from, to: query.to, page: String(page) }); for (const [key, value] of [...params]) if (!value || (key === "page" && value === "1")) params.delete(key); return `/deals?${params}`; };
  return <div className="mx-auto max-w-[1250px]"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#728179]">Doanh thu</p><h1 className="mt-2 text-3xl font-bold tracking-[-.035em] sm:text-4xl">Giao dịch</h1><p className="mt-2 text-sm text-[#718078]">Theo dõi đăng ký và doanh thu VND trong phạm vi của bạn.</p></div><Link href="/customers" className="focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#176a4f] px-4 text-sm font-bold text-white"><ContactRound size={17} /> Chọn khách để đăng ký</Link></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-5"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Banknote size={19} /></span><p className="mt-4 text-sm font-semibold text-[#68776f]">Doanh thu đang hiệu lực</p><p className="mt-1 text-2xl font-bold">{money.format(data.pageTotal)}</p></div><div className="rounded-2xl border border-[#dfe7e2] bg-white p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#edf2e4] text-[#526c3b]"><ReceiptText size={19} /></span><p className="mt-4 text-sm font-semibold text-[#68776f]">Số giao dịch phù hợp</p><p className="mt-1 text-2xl font-bold">{data.count}</p></div></section>
    <section className="card-shadow mt-5 rounded-[22px] border border-[#dfe7e2] bg-white"><form method="get" className="grid gap-3 border-b border-[#e4ebe7] p-4 md:grid-cols-2 xl:grid-cols-4"><select name="status" defaultValue={query.status} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="active">Đang hiệu lực</option><option value="void">Đã hủy</option><option value="all">Mọi trạng thái</option></select><select name="owner" defaultValue={query.owner} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="">Mọi tư vấn viên</option>{data.owners.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="team" defaultValue={query.team} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="">Mọi nhóm</option>{data.teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="source" defaultValue={query.source} className="focus-ring min-h-11 rounded-xl border border-[#d8e2dc] px-3 text-sm"><option value="">Mọi nguồn</option>{data.sources.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="text-xs font-bold text-[#617168]">Từ ngày<input type="date" name="from" defaultValue={query.from} className="focus-ring mt-1 min-h-11 w-full rounded-xl border border-[#d8e2dc] px-3 text-sm" /></label><label className="text-xs font-bold text-[#617168]">Đến ngày<input type="date" name="to" defaultValue={query.to} className="focus-ring mt-1 min-h-11 w-full rounded-xl border border-[#d8e2dc] px-3 text-sm" /></label><button className="focus-ring min-h-11 self-end rounded-xl border border-[#cbd8d0] text-sm font-bold text-[#315d49]">Áp dụng bộ lọc</button></form>
      <div className="p-4 sm:p-5">{data.deals.length ? <div className="grid gap-4 lg:grid-cols-2">{data.deals.map((deal) => <div key={deal.id} className="rounded-2xl bg-[#f7f9f7] p-3"><div className="mb-2 flex items-center justify-between gap-3 px-1"><Link href={`/customers?customer=${deal.customerId}`} className="focus-ring rounded-md text-sm font-bold text-[#176a4f] hover:underline">{deal.customerName}</Link><span className="text-xs text-[#7b8982]">{deal.teamName}</span></div><DealCard deal={deal} viewer={data.viewer} amendmentKey={amendmentKeys[deal.id] ?? ""} /></div>)}</div> : <div className="grid min-h-60 place-items-center text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#edf2e4] text-[#526c3b]"><ReceiptText size={21} /></span><p className="mt-4 font-bold">Chưa có giao dịch phù hợp</p><p className="mt-1 text-sm text-[#7b8982]">Chọn một khách hàng để ghi nhận đăng ký đầu tiên.</p></div></div>}</div>
      <footer className="flex items-center justify-between border-t border-[#e9eeeb] px-4 py-4 text-sm text-[#69776f]"><span>Trang {query.page}/{totalPages}</span><div className="flex gap-2"><Link href={href(Math.max(1, query.page - 1))} aria-disabled={query.page <= 1} className={`focus-ring grid size-10 place-items-center rounded-xl border border-[#dbe3de] ${query.page <= 1 ? "pointer-events-none opacity-40" : ""}`}><ChevronLeft size={17} /></Link><Link href={href(Math.min(totalPages, query.page + 1))} aria-disabled={query.page >= totalPages} className={`focus-ring grid size-10 place-items-center rounded-xl border border-[#dbe3de] ${query.page >= totalPages ? "pointer-events-none opacity-40" : ""}`}><ChevronRight size={17} /></Link></div></footer>
    </section></div>;
}
